## Ustreamer base Service
x-ustreamer-svc: &ustreamer-svc
  image: mkuf/ustreamer:latest
  restart: unless-stopped
  command: --host=0.0.0.0 --port=8080 --slowdown --device=/dev/webcam --resolution=1280x960 --format=MJPEG --desired-fps=30


# use mounted sd card as a volume for gcodes
volumes:
  gcode:
    driver: local
    driver_opts:
      type: ext4
      device: /dev/sda1

## Add your personal config here
services:
  klipper:
    devices:
      - /dev/ttyACM0:/dev/ttymxc3
    command:
      - "-I"
      - "run/klipper.tty"
      - "-a"
      - "run/klipper.sock"
      - "cfg/custom-config/printer.cfg"
      - "-l"
      - "log/klippy.log"

  # webcam:
  #   <<: *ustreamer-svc
  #   devices:
  #     - /dev/video0:/dev/webcam
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.services.webcam.loadbalancer.server.port=8080"
  #     - "traefik.http.routers.webcam.rule=PathPrefix(`/webcam`)"
  #     - "traefik.http.routers.webcam.entrypoints=web"
  #     - "traefik.http.middlewares.webcam.stripprefix.prefixes=/webcam"
  #     - "traefik.http.routers.webcam.middlewares=webcam"
